is09_features = '''
@attribute pcm_RMSenergy_sma_max numeric
@attribute pcm_RMSenergy_sma_min numeric
@attribute pcm_RMSenergy_sma_range numeric
@attribute pcm_RMSenergy_sma_maxPos numeric
@attribute pcm_RMSenergy_sma_minPos numeric
@attribute pcm_RMSenergy_sma_amean numeric
@attribute pcm_RMSenergy_sma_linregc1 numeric
@attribute pcm_RMSenergy_sma_linregc2 numeric
@attribute pcm_RMSenergy_sma_linregerrQ numeric
@attribute pcm_RMSenergy_sma_stddev numeric
@attribute pcm_RMSenergy_sma_skewness numeric
@attribute pcm_RMSenergy_sma_kurtosis numeric
@attribute pcm_fftMag_mfcc_sma[1]_max numeric
@attribute pcm_fftMag_mfcc_sma[1]_min numeric
@attribute pcm_fftMag_mfcc_sma[1]_range numeric
@attribute pcm_fftMag_mfcc_sma[1]_maxPos numeric
@attribute pcm_fftMag_mfcc_sma[1]_minPos numeric
@attribute pcm_fftMag_mfcc_sma[1]_amean numeric
@attribute pcm_fftMag_mfcc_sma[1]_linregc1 numeric
@attribute pcm_fftMag_mfcc_sma[1]_linregc2 numeric
@attribute pcm_fftMag_mfcc_sma[1]_linregerrQ numeric
@attribute pcm_fftMag_mfcc_sma[1]_stddev numeric
@attribute pcm_fftMag_mfcc_sma[1]_skewness numeric
@attribute pcm_fftMag_mfcc_sma[1]_kurtosis numeric
@attribute pcm_fftMag_mfcc_sma[2]_max numeric
@attribute pcm_fftMag_mfcc_sma[2]_min numeric
@attribute pcm_fftMag_mfcc_sma[2]_range numeric
@attribute pcm_fftMag_mfcc_sma[2]_maxPos numeric
@attribute pcm_fftMag_mfcc_sma[2]_minPos numeric
@attribute pcm_fftMag_mfcc_sma[2]_amean numeric
@attribute pcm_fftMag_mfcc_sma[2]_linregc1 numeric
@attribute pcm_fftMag_mfcc_sma[2]_linregc2 numeric
@attribute pcm_fftMag_mfcc_sma[2]_linregerrQ numeric
@attribute pcm_fftMag_mfcc_sma[2]_stddev numeric
@attribute pcm_fftMag_mfcc_sma[2]_skewness numeric
@attribute pcm_fftMag_mfcc_sma[2]_kurtosis numeric
@attribute pcm_fftMag_mfcc_sma[3]_max numeric
@attribute pcm_fftMag_mfcc_sma[3]_min numeric
@attribute pcm_fftMag_mfcc_sma[3]_range numeric
@attribute pcm_fftMag_mfcc_sma[3]_maxPos numeric
@attribute pcm_fftMag_mfcc_sma[3]_minPos numeric
@attribute pcm_fftMag_mfcc_sma[3]_amean numeric
@attribute pcm_fftMag_mfcc_sma[3]_linregc1 numeric
@attribute pcm_fftMag_mfcc_sma[3]_linregc2 numeric
@attribute pcm_fftMag_mfcc_sma[3]_linregerrQ numeric
@attribute pcm_fftMag_mfcc_sma[3]_stddev numeric
@attribute pcm_fftMag_mfcc_sma[3]_skewness numeric
@attribute pcm_fftMag_mfcc_sma[3]_kurtosis numeric
@attribute pcm_fftMag_mfcc_sma[4]_max numeric
@attribute pcm_fftMag_mfcc_sma[4]_min numeric
@attribute pcm_fftMag_mfcc_sma[4]_range numeric
@attribute pcm_fftMag_mfcc_sma[4]_maxPos numeric
@attribute pcm_fftMag_mfcc_sma[4]_minPos numeric
@attribute pcm_fftMag_mfcc_sma[4]_amean numeric
@attribute pcm_fftMag_mfcc_sma[4]_linregc1 numeric
@attribute pcm_fftMag_mfcc_sma[4]_linregc2 numeric
@attribute pcm_fftMag_mfcc_sma[4]_linregerrQ numeric
@attribute pcm_fftMag_mfcc_sma[4]_stddev numeric
@attribute pcm_fftMag_mfcc_sma[4]_skewness numeric
@attribute pcm_fftMag_mfcc_sma[4]_kurtosis numeric
@attribute pcm_fftMag_mfcc_sma[5]_max numeric
@attribute pcm_fftMag_mfcc_sma[5]_min numeric
@attribute pcm_fftMag_mfcc_sma[5]_range numeric
@attribute pcm_fftMag_mfcc_sma[5]_maxPos numeric
@attribute pcm_fftMag_mfcc_sma[5]_minPos numeric
@attribute pcm_fftMag_mfcc_sma[5]_amean numeric
@attribute pcm_fftMag_mfcc_sma[5]_linregc1 numeric
@attribute pcm_fftMag_mfcc_sma[5]_linregc2 numeric
@attribute pcm_fftMag_mfcc_sma[5]_linregerrQ numeric
@attribute pcm_fftMag_mfcc_sma[5]_stddev numeric
@attribute pcm_fftMag_mfcc_sma[5]_skewness numeric
@attribute pcm_fftMag_mfcc_sma[5]_kurtosis numeric
@attribute pcm_fftMag_mfcc_sma[6]_max numeric
@attribute pcm_fftMag_mfcc_sma[6]_min numeric
@attribute pcm_fftMag_mfcc_sma[6]_range numeric
@attribute pcm_fftMag_mfcc_sma[6]_maxPos numeric
@attribute pcm_fftMag_mfcc_sma[6]_minPos numeric
@attribute pcm_fftMag_mfcc_sma[6]_amean numeric
@attribute pcm_fftMag_mfcc_sma[6]_linregc1 numeric
@attribute pcm_fftMag_mfcc_sma[6]_linregc2 numeric
@attribute pcm_fftMag_mfcc_sma[6]_linregerrQ numeric
@attribute pcm_fftMag_mfcc_sma[6]_stddev numeric
@attribute pcm_fftMag_mfcc_sma[6]_skewness numeric
@attribute pcm_fftMag_mfcc_sma[6]_kurtosis numeric
@attribute pcm_fftMag_mfcc_sma[7]_max numeric
@attribute pcm_fftMag_mfcc_sma[7]_min numeric
@attribute pcm_fftMag_mfcc_sma[7]_range numeric
@attribute pcm_fftMag_mfcc_sma[7]_maxPos numeric
@attribute pcm_fftMag_mfcc_sma[7]_minPos numeric
@attribute pcm_fftMag_mfcc_sma[7]_amean numeric
@attribute pcm_fftMag_mfcc_sma[7]_linregc1 numeric
@attribute pcm_fftMag_mfcc_sma[7]_linregc2 numeric
@attribute pcm_fftMag_mfcc_sma[7]_linregerrQ numeric
@attribute pcm_fftMag_mfcc_sma[7]_stddev numeric
@attribute pcm_fftMag_mfcc_sma[7]_skewness numeric
@attribute pcm_fftMag_mfcc_sma[7]_kurtosis numeric
@attribute pcm_fftMag_mfcc_sma[8]_max numeric
@attribute pcm_fftMag_mfcc_sma[8]_min numeric
@attribute pcm_fftMag_mfcc_sma[8]_range numeric
@attribute pcm_fftMag_mfcc_sma[8]_maxPos numeric
@attribute pcm_fftMag_mfcc_sma[8]_minPos numeric
@attribute pcm_fftMag_mfcc_sma[8]_amean numeric
@attribute pcm_fftMag_mfcc_sma[8]_linregc1 numeric
@attribute pcm_fftMag_mfcc_sma[8]_linregc2 numeric
@attribute pcm_fftMag_mfcc_sma[8]_linregerrQ numeric
@attribute pcm_fftMag_mfcc_sma[8]_stddev numeric
@attribute pcm_fftMag_mfcc_sma[8]_skewness numeric
@attribute pcm_fftMag_mfcc_sma[8]_kurtosis numeric
@attribute pcm_fftMag_mfcc_sma[9]_max numeric
@attribute pcm_fftMag_mfcc_sma[9]_min numeric
@attribute pcm_fftMag_mfcc_sma[9]_range numeric
@attribute pcm_fftMag_mfcc_sma[9]_maxPos numeric
@attribute pcm_fftMag_mfcc_sma[9]_minPos numeric
@attribute pcm_fftMag_mfcc_sma[9]_amean numeric
@attribute pcm_fftMag_mfcc_sma[9]_linregc1 numeric
@attribute pcm_fftMag_mfcc_sma[9]_linregc2 numeric
@attribute pcm_fftMag_mfcc_sma[9]_linregerrQ numeric
@attribute pcm_fftMag_mfcc_sma[9]_stddev numeric
@attribute pcm_fftMag_mfcc_sma[9]_skewness numeric
@attribute pcm_fftMag_mfcc_sma[9]_kurtosis numeric
@attribute pcm_fftMag_mfcc_sma[10]_max numeric
@attribute pcm_fftMag_mfcc_sma[10]_min numeric
@attribute pcm_fftMag_mfcc_sma[10]_range numeric
@attribute pcm_fftMag_mfcc_sma[10]_maxPos numeric
@attribute pcm_fftMag_mfcc_sma[10]_minPos numeric
@attribute pcm_fftMag_mfcc_sma[10]_amean numeric
@attribute pcm_fftMag_mfcc_sma[10]_linregc1 numeric
@attribute pcm_fftMag_mfcc_sma[10]_linregc2 numeric
@attribute pcm_fftMag_mfcc_sma[10]_linregerrQ numeric
@attribute pcm_fftMag_mfcc_sma[10]_stddev numeric
@attribute pcm_fftMag_mfcc_sma[10]_skewness numeric
@attribute pcm_fftMag_mfcc_sma[10]_kurtosis numeric
@attribute pcm_fftMag_mfcc_sma[11]_max numeric
@attribute pcm_fftMag_mfcc_sma[11]_min numeric
@attribute pcm_fftMag_mfcc_sma[11]_range numeric
@attribute pcm_fftMag_mfcc_sma[11]_maxPos numeric
@attribute pcm_fftMag_mfcc_sma[11]_minPos numeric
@attribute pcm_fftMag_mfcc_sma[11]_amean numeric
@attribute pcm_fftMag_mfcc_sma[11]_linregc1 numeric
@attribute pcm_fftMag_mfcc_sma[11]_linregc2 numeric
@attribute pcm_fftMag_mfcc_sma[11]_linregerrQ numeric
@attribute pcm_fftMag_mfcc_sma[11]_stddev numeric
@attribute pcm_fftMag_mfcc_sma[11]_skewness numeric
@attribute pcm_fftMag_mfcc_sma[11]_kurtosis numeric
@attribute pcm_fftMag_mfcc_sma[12]_max numeric
@attribute pcm_fftMag_mfcc_sma[12]_min numeric
@attribute pcm_fftMag_mfcc_sma[12]_range numeric
@attribute pcm_fftMag_mfcc_sma[12]_maxPos numeric
@attribute pcm_fftMag_mfcc_sma[12]_minPos numeric
@attribute pcm_fftMag_mfcc_sma[12]_amean numeric
@attribute pcm_fftMag_mfcc_sma[12]_linregc1 numeric
@attribute pcm_fftMag_mfcc_sma[12]_linregc2 numeric
@attribute pcm_fftMag_mfcc_sma[12]_linregerrQ numeric
@attribute pcm_fftMag_mfcc_sma[12]_stddev numeric
@attribute pcm_fftMag_mfcc_sma[12]_skewness numeric
@attribute pcm_fftMag_mfcc_sma[12]_kurtosis numeric
@attribute pcm_zcr_sma_max numeric
@attribute pcm_zcr_sma_min numeric
@attribute pcm_zcr_sma_range numeric
@attribute pcm_zcr_sma_maxPos numeric
@attribute pcm_zcr_sma_minPos numeric
@attribute pcm_zcr_sma_amean numeric
@attribute pcm_zcr_sma_linregc1 numeric
@attribute pcm_zcr_sma_linregc2 numeric
@attribute pcm_zcr_sma_linregerrQ numeric
@attribute pcm_zcr_sma_stddev numeric
@attribute pcm_zcr_sma_skewness numeric
@attribute pcm_zcr_sma_kurtosis numeric
@attribute voiceProb_sma_max numeric
@attribute voiceProb_sma_min numeric
@attribute voiceProb_sma_range numeric
@attribute voiceProb_sma_maxPos numeric
@attribute voiceProb_sma_minPos numeric
@attribute voiceProb_sma_amean numeric
@attribute voiceProb_sma_linregc1 numeric
@attribute voiceProb_sma_linregc2 numeric
@attribute voiceProb_sma_linregerrQ numeric
@attribute voiceProb_sma_stddev numeric
@attribute voiceProb_sma_skewness numeric
@attribute voiceProb_sma_kurtosis numeric
@attribute F0_sma_max numeric
@attribute F0_sma_min numeric
@attribute F0_sma_range numeric
@attribute F0_sma_maxPos numeric
@attribute F0_sma_minPos numeric
@attribute F0_sma_amean numeric
@attribute F0_sma_linregc1 numeric
@attribute F0_sma_linregc2 numeric
@attribute F0_sma_linregerrQ numeric
@attribute F0_sma_stddev numeric
@attribute F0_sma_skewness numeric
@attribute F0_sma_kurtosis numeric
@attribute pcm_RMSenergy_sma_de_max numeric
@attribute pcm_RMSenergy_sma_de_min numeric
@attribute pcm_RMSenergy_sma_de_range numeric
@attribute pcm_RMSenergy_sma_de_maxPos numeric
@attribute pcm_RMSenergy_sma_de_minPos numeric
@attribute pcm_RMSenergy_sma_de_amean numeric
@attribute pcm_RMSenergy_sma_de_linregc1 numeric
@attribute pcm_RMSenergy_sma_de_linregc2 numeric
@attribute pcm_RMSenergy_sma_de_linregerrQ numeric
@attribute pcm_RMSenergy_sma_de_stddev numeric
@attribute pcm_RMSenergy_sma_de_skewness numeric
@attribute pcm_RMSenergy_sma_de_kurtosis numeric
@attribute pcm_fftMag_mfcc_sma_de[1]_max numeric
@attribute pcm_fftMag_mfcc_sma_de[1]_min numeric
@attribute pcm_fftMag_mfcc_sma_de[1]_range numeric
@attribute pcm_fftMag_mfcc_sma_de[1]_maxPos numeric
@attribute pcm_fftMag_mfcc_sma_de[1]_minPos numeric
@attribute pcm_fftMag_mfcc_sma_de[1]_amean numeric
@attribute pcm_fftMag_mfcc_sma_de[1]_linregc1 numeric
@attribute pcm_fftMag_mfcc_sma_de[1]_linregc2 numeric
@attribute pcm_fftMag_mfcc_sma_de[1]_linregerrQ numeric
@attribute pcm_fftMag_mfcc_sma_de[1]_stddev numeric
@attribute pcm_fftMag_mfcc_sma_de[1]_skewness numeric
@attribute pcm_fftMag_mfcc_sma_de[1]_kurtosis numeric
@attribute pcm_fftMag_mfcc_sma_de[2]_max numeric
@attribute pcm_fftMag_mfcc_sma_de[2]_min numeric
@attribute pcm_fftMag_mfcc_sma_de[2]_range numeric
@attribute pcm_fftMag_mfcc_sma_de[2]_maxPos numeric
@attribute pcm_fftMag_mfcc_sma_de[2]_minPos numeric
@attribute pcm_fftMag_mfcc_sma_de[2]_amean numeric
@attribute pcm_fftMag_mfcc_sma_de[2]_linregc1 numeric
@attribute pcm_fftMag_mfcc_sma_de[2]_linregc2 numeric
@attribute pcm_fftMag_mfcc_sma_de[2]_linregerrQ numeric
@attribute pcm_fftMag_mfcc_sma_de[2]_stddev numeric
@attribute pcm_fftMag_mfcc_sma_de[2]_skewness numeric
@attribute pcm_fftMag_mfcc_sma_de[2]_kurtosis numeric
@attribute pcm_fftMag_mfcc_sma_de[3]_max numeric
@attribute pcm_fftMag_mfcc_sma_de[3]_min numeric
@attribute pcm_fftMag_mfcc_sma_de[3]_range numeric
@attribute pcm_fftMag_mfcc_sma_de[3]_maxPos numeric
@attribute pcm_fftMag_mfcc_sma_de[3]_minPos numeric
@attribute pcm_fftMag_mfcc_sma_de[3]_amean numeric
@attribute pcm_fftMag_mfcc_sma_de[3]_linregc1 numeric
@attribute pcm_fftMag_mfcc_sma_de[3]_linregc2 numeric
@attribute pcm_fftMag_mfcc_sma_de[3]_linregerrQ numeric
@attribute pcm_fftMag_mfcc_sma_de[3]_stddev numeric
@attribute pcm_fftMag_mfcc_sma_de[3]_skewness numeric
@attribute pcm_fftMag_mfcc_sma_de[3]_kurtosis numeric
@attribute pcm_fftMag_mfcc_sma_de[4]_max numeric
@attribute pcm_fftMag_mfcc_sma_de[4]_min numeric
@attribute pcm_fftMag_mfcc_sma_de[4]_range numeric
@attribute pcm_fftMag_mfcc_sma_de[4]_maxPos numeric
@attribute pcm_fftMag_mfcc_sma_de[4]_minPos numeric
@attribute pcm_fftMag_mfcc_sma_de[4]_amean numeric
@attribute pcm_fftMag_mfcc_sma_de[4]_linregc1 numeric
@attribute pcm_fftMag_mfcc_sma_de[4]_linregc2 numeric
@attribute pcm_fftMag_mfcc_sma_de[4]_linregerrQ numeric
@attribute pcm_fftMag_mfcc_sma_de[4]_stddev numeric
@attribute pcm_fftMag_mfcc_sma_de[4]_skewness numeric
@attribute pcm_fftMag_mfcc_sma_de[4]_kurtosis numeric
@attribute pcm_fftMag_mfcc_sma_de[5]_max numeric
@attribute pcm_fftMag_mfcc_sma_de[5]_min numeric
@attribute pcm_fftMag_mfcc_sma_de[5]_range numeric
@attribute pcm_fftMag_mfcc_sma_de[5]_maxPos numeric
@attribute pcm_fftMag_mfcc_sma_de[5]_minPos numeric
@attribute pcm_fftMag_mfcc_sma_de[5]_amean numeric
@attribute pcm_fftMag_mfcc_sma_de[5]_linregc1 numeric
@attribute pcm_fftMag_mfcc_sma_de[5]_linregc2 numeric
@attribute pcm_fftMag_mfcc_sma_de[5]_linregerrQ numeric
@attribute pcm_fftMag_mfcc_sma_de[5]_stddev numeric
@attribute pcm_fftMag_mfcc_sma_de[5]_skewness numeric
@attribute pcm_fftMag_mfcc_sma_de[5]_kurtosis numeric
@attribute pcm_fftMag_mfcc_sma_de[6]_max numeric
@attribute pcm_fftMag_mfcc_sma_de[6]_min numeric
@attribute pcm_fftMag_mfcc_sma_de[6]_range numeric
@attribute pcm_fftMag_mfcc_sma_de[6]_maxPos numeric
@attribute pcm_fftMag_mfcc_sma_de[6]_minPos numeric
@attribute pcm_fftMag_mfcc_sma_de[6]_amean numeric
@attribute pcm_fftMag_mfcc_sma_de[6]_linregc1 numeric
@attribute pcm_fftMag_mfcc_sma_de[6]_linregc2 numeric
@attribute pcm_fftMag_mfcc_sma_de[6]_linregerrQ numeric
@attribute pcm_fftMag_mfcc_sma_de[6]_stddev numeric
@attribute pcm_fftMag_mfcc_sma_de[6]_skewness numeric
@attribute pcm_fftMag_mfcc_sma_de[6]_kurtosis numeric
@attribute pcm_fftMag_mfcc_sma_de[7]_max numeric
@attribute pcm_fftMag_mfcc_sma_de[7]_min numeric
@attribute pcm_fftMag_mfcc_sma_de[7]_range numeric
@attribute pcm_fftMag_mfcc_sma_de[7]_maxPos numeric
@attribute pcm_fftMag_mfcc_sma_de[7]_minPos numeric
@attribute pcm_fftMag_mfcc_sma_de[7]_amean numeric
@attribute pcm_fftMag_mfcc_sma_de[7]_linregc1 numeric
@attribute pcm_fftMag_mfcc_sma_de[7]_linregc2 numeric
@attribute pcm_fftMag_mfcc_sma_de[7]_linregerrQ numeric
@attribute pcm_fftMag_mfcc_sma_de[7]_stddev numeric
@attribute pcm_fftMag_mfcc_sma_de[7]_skewness numeric
@attribute pcm_fftMag_mfcc_sma_de[7]_kurtosis numeric
@attribute pcm_fftMag_mfcc_sma_de[8]_max numeric
@attribute pcm_fftMag_mfcc_sma_de[8]_min numeric
@attribute pcm_fftMag_mfcc_sma_de[8]_range numeric
@attribute pcm_fftMag_mfcc_sma_de[8]_maxPos numeric
@attribute pcm_fftMag_mfcc_sma_de[8]_minPos numeric
@attribute pcm_fftMag_mfcc_sma_de[8]_amean numeric
@attribute pcm_fftMag_mfcc_sma_de[8]_linregc1 numeric
@attribute pcm_fftMag_mfcc_sma_de[8]_linregc2 numeric
@attribute pcm_fftMag_mfcc_sma_de[8]_linregerrQ numeric
@attribute pcm_fftMag_mfcc_sma_de[8]_stddev numeric
@attribute pcm_fftMag_mfcc_sma_de[8]_skewness numeric
@attribute pcm_fftMag_mfcc_sma_de[8]_kurtosis numeric
@attribute pcm_fftMag_mfcc_sma_de[9]_max numeric
@attribute pcm_fftMag_mfcc_sma_de[9]_min numeric
@attribute pcm_fftMag_mfcc_sma_de[9]_range numeric
@attribute pcm_fftMag_mfcc_sma_de[9]_maxPos numeric
@attribute pcm_fftMag_mfcc_sma_de[9]_minPos numeric
@attribute pcm_fftMag_mfcc_sma_de[9]_amean numeric
@attribute pcm_fftMag_mfcc_sma_de[9]_linregc1 numeric
@attribute pcm_fftMag_mfcc_sma_de[9]_linregc2 numeric
@attribute pcm_fftMag_mfcc_sma_de[9]_linregerrQ numeric
@attribute pcm_fftMag_mfcc_sma_de[9]_stddev numeric
@attribute pcm_fftMag_mfcc_sma_de[9]_skewness numeric
@attribute pcm_fftMag_mfcc_sma_de[9]_kurtosis numeric
@attribute pcm_fftMag_mfcc_sma_de[10]_max numeric
@attribute pcm_fftMag_mfcc_sma_de[10]_min numeric
@attribute pcm_fftMag_mfcc_sma_de[10]_range numeric
@attribute pcm_fftMag_mfcc_sma_de[10]_maxPos numeric
@attribute pcm_fftMag_mfcc_sma_de[10]_minPos numeric
@attribute pcm_fftMag_mfcc_sma_de[10]_amean numeric
@attribute pcm_fftMag_mfcc_sma_de[10]_linregc1 numeric
@attribute pcm_fftMag_mfcc_sma_de[10]_linregc2 numeric
@attribute pcm_fftMag_mfcc_sma_de[10]_linregerrQ numeric
@attribute pcm_fftMag_mfcc_sma_de[10]_stddev numeric
@attribute pcm_fftMag_mfcc_sma_de[10]_skewness numeric
@attribute pcm_fftMag_mfcc_sma_de[10]_kurtosis numeric
@attribute pcm_fftMag_mfcc_sma_de[11]_max numeric
@attribute pcm_fftMag_mfcc_sma_de[11]_min numeric
@attribute pcm_fftMag_mfcc_sma_de[11]_range numeric
@attribute pcm_fftMag_mfcc_sma_de[11]_maxPos numeric
@attribute pcm_fftMag_mfcc_sma_de[11]_minPos numeric
@attribute pcm_fftMag_mfcc_sma_de[11]_amean numeric
@attribute pcm_fftMag_mfcc_sma_de[11]_linregc1 numeric
@attribute pcm_fftMag_mfcc_sma_de[11]_linregc2 numeric
@attribute pcm_fftMag_mfcc_sma_de[11]_linregerrQ numeric
@attribute pcm_fftMag_mfcc_sma_de[11]_stddev numeric
@attribute pcm_fftMag_mfcc_sma_de[11]_skewness numeric
@attribute pcm_fftMag_mfcc_sma_de[11]_kurtosis numeric
@attribute pcm_fftMag_mfcc_sma_de[12]_max numeric
@attribute pcm_fftMag_mfcc_sma_de[12]_min numeric
@attribute pcm_fftMag_mfcc_sma_de[12]_range numeric
@attribute pcm_fftMag_mfcc_sma_de[12]_maxPos numeric
@attribute pcm_fftMag_mfcc_sma_de[12]_minPos numeric
@attribute pcm_fftMag_mfcc_sma_de[12]_amean numeric
@attribute pcm_fftMag_mfcc_sma_de[12]_linregc1 numeric
@attribute pcm_fftMag_mfcc_sma_de[12]_linregc2 numeric
@attribute pcm_fftMag_mfcc_sma_de[12]_linregerrQ numeric
@attribute pcm_fftMag_mfcc_sma_de[12]_stddev numeric
@attribute pcm_fftMag_mfcc_sma_de[12]_skewness numeric
@attribute pcm_fftMag_mfcc_sma_de[12]_kurtosis numeric
@attribute pcm_zcr_sma_de_max numeric
@attribute pcm_zcr_sma_de_min numeric
@attribute pcm_zcr_sma_de_range numeric
@attribute pcm_zcr_sma_de_maxPos numeric
@attribute pcm_zcr_sma_de_minPos numeric
@attribute pcm_zcr_sma_de_amean numeric
@attribute pcm_zcr_sma_de_linregc1 numeric
@attribute pcm_zcr_sma_de_linregc2 numeric
@attribute pcm_zcr_sma_de_linregerrQ numeric
@attribute pcm_zcr_sma_de_stddev numeric
@attribute pcm_zcr_sma_de_skewness numeric
@attribute pcm_zcr_sma_de_kurtosis numeric
@attribute voiceProb_sma_de_max numeric
@attribute voiceProb_sma_de_min numeric
@attribute voiceProb_sma_de_range numeric
@attribute voiceProb_sma_de_maxPos numeric
@attribute voiceProb_sma_de_minPos numeric
@attribute voiceProb_sma_de_amean numeric
@attribute voiceProb_sma_de_linregc1 numeric
@attribute voiceProb_sma_de_linregc2 numeric
@attribute voiceProb_sma_de_linregerrQ numeric
@attribute voiceProb_sma_de_stddev numeric
@attribute voiceProb_sma_de_skewness numeric
@attribute voiceProb_sma_de_kurtosis numeric
@attribute F0_sma_de_max numeric
@attribute F0_sma_de_min numeric
@attribute F0_sma_de_range numeric
@attribute F0_sma_de_maxPos numeric
@attribute F0_sma_de_minPos numeric
@attribute F0_sma_de_amean numeric
@attribute F0_sma_de_linregc1 numeric
@attribute F0_sma_de_linregc2 numeric
@attribute F0_sma_de_linregerrQ numeric
@attribute F0_sma_de_stddev numeric
@attribute F0_sma_de_skewness numeric
@attribute F0_sma_de_kurtosis numeric
'''

egemaps_features = '''
@attribute F0semitoneFrom27.5Hz_sma3nz_amean numeric
@attribute F0semitoneFrom27.5Hz_sma3nz_stddevNorm numeric
@attribute F0semitoneFrom27.5Hz_sma3nz_percentile20.0 numeric
@attribute F0semitoneFrom27.5Hz_sma3nz_percentile50.0 numeric
@attribute F0semitoneFrom27.5Hz_sma3nz_percentile80.0 numeric
@attribute F0semitoneFrom27.5Hz_sma3nz_pctlrange0-2 numeric
@attribute F0semitoneFrom27.5Hz_sma3nz_meanRisingSlope numeric
@attribute F0semitoneFrom27.5Hz_sma3nz_stddevRisingSlope numeric
@attribute F0semitoneFrom27.5Hz_sma3nz_meanFallingSlope numeric
@attribute F0semitoneFrom27.5Hz_sma3nz_stddevFallingSlope numeric
@attribute loudness_sma3_amean numeric
@attribute loudness_sma3_stddevNorm numeric
@attribute loudness_sma3_percentile20.0 numeric
@attribute loudness_sma3_percentile50.0 numeric
@attribute loudness_sma3_percentile80.0 numeric
@attribute loudness_sma3_pctlrange0-2 numeric
@attribute loudness_sma3_meanRisingSlope numeric
@attribute loudness_sma3_stddevRisingSlope numeric
@attribute loudness_sma3_meanFallingSlope numeric
@attribute loudness_sma3_stddevFallingSlope numeric
@attribute jitterLocal_sma3nz_amean numeric
@attribute jitterLocal_sma3nz_stddevNorm numeric
@attribute shimmerLocaldB_sma3nz_amean numeric
@attribute shimmerLocaldB_sma3nz_stddevNorm numeric
@attribute HNRdBACF_sma3nz_amean numeric
@attribute HNRdBACF_sma3nz_stddevNorm numeric
@attribute logRelF0-H1-H2_sma3nz_amean numeric
@attribute logRelF0-H1-H2_sma3nz_stddevNorm numeric
@attribute logRelF0-H1-A3_sma3nz_amean numeric
@attribute logRelF0-H1-A3_sma3nz_stddevNorm numeric
@attribute F1frequency_sma3nz_amean numeric
@attribute F1frequency_sma3nz_stddevNorm numeric
@attribute F1bandwidth_sma3nz_amean numeric
@attribute F1bandwidth_sma3nz_stddevNorm numeric
@attribute F1amplitudeLogRelF0_sma3nz_amean numeric
@attribute F1amplitudeLogRelF0_sma3nz_stddevNorm numeric
@attribute F2frequency_sma3nz_amean numeric
@attribute F2frequency_sma3nz_stddevNorm numeric
@attribute F2amplitudeLogRelF0_sma3nz_amean numeric
@attribute F2amplitudeLogRelF0_sma3nz_stddevNorm numeric
@attribute F3frequency_sma3nz_amean numeric
@attribute F3frequency_sma3nz_stddevNorm numeric
@attribute F3amplitudeLogRelF0_sma3nz_amean numeric
@attribute F3amplitudeLogRelF0_sma3nz_stddevNorm numeric
@attribute alphaRatioV_sma3nz_amean numeric
@attribute alphaRatioV_sma3nz_stddevNorm numeric
@attribute hammarbergIndexV_sma3nz_amean numeric
@attribute hammarbergIndexV_sma3nz_stddevNorm numeric
@attribute slopeV0-500_sma3nz_amean numeric
@attribute slopeV0-500_sma3nz_stddevNorm numeric
@attribute slopeV500-1500_sma3nz_amean numeric
@attribute slopeV500-1500_sma3nz_stddevNorm numeric
@attribute alphaRatioUV_sma3nz_amean numeric
@attribute hammarbergIndexUV_sma3nz_amean numeric
@attribute slopeUV0-500_sma3nz_amean numeric
@attribute slopeUV500-1500_sma3nz_amean numeric
@attribute loudnessPeaksPerSec numeric
@attribute VoicedSegmentsPerSec numeric
@attribute MeanVoicedSegmentLengthSec numeric
@attribute StddevVoicedSegmentLengthSec numeric
@attribute MeanUnvoicedSegmentLength numeric
@attribute StddevUnvoicedSegmentLength numeric
'''

is09 = is09_features.split('@attribute')
is09 = [x.strip() for x in is09]
# remove \n from the end of each attribute
is09 = [x.split(' ')[0] for x in is09]
# remove any empty strings
is09 = [x for x in is09 if x]
print(is09)